version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - misspell
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (net.PacketConn).WriteTo
        - (net.Conn).Write
        - encoding/json.MarshalIndent
        - (*github.com/pion/dtls/v3.Conn).SetDeadline
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: blank-imports
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - errcheck
      source: "doRequest|packetPool\\.Get"
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
